global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: [ ]
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: anern_monitoring
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 'anern_monitoring:8081'
  - job_name: sonoff_manager
    honor_timestamps: true
    metrics_path: /metrics
    scheme: http
    scrape_interval: 60s
    static_configs:
      - targets:
          - '192.168.25.125:9006'
  - job_name: prometheus
    static_configs:
      - targets:
          - 'localhost:9090'

  - job_name: "hass"
    scrape_interval: 10s
    metrics_path: /api/prometheus

    # Long-Lived Access Token
    bearer_token: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIwNWE5NTM1YzViNzI0YjNhOTVjNzJlNmFmZjU2N2EzNSIsImlhdCI6MTcxMjQwOTQ1NiwiZXhwIjoyMDI3NzY5NDU2fQ.fcehX6bhAzPDgcdjFI7R_JvavJZ-zpkoHtFxa0mdRxg"

    scheme: http
    static_configs:
      - targets: ['192.168.25.125:8123']
